#!/usr/bin/env bash
# Pre-tool hook for Claude Code and Kiro CLI: blocks posting GitHub comments, replies or reviews
# (gh via the shell tool) and Jira comments (Atlassian MCP) unless the text contains the calling
# agent's prefix: "[Generated by Claude]" or "[Generated by Kiro]".
set -euo pipefail

input="$(cat)"
tool_name="$(jq -r '.tool_name // ""' <<<"$input")"

# Kiro CLI names the event "preToolUse"; Claude Code names it "PreToolUse".
is_kiro=false
[[ "$(jq -r '.hook_event_name // ""' <<<"$input")" == "preToolUse" ]] && is_kiro=true

PREFIX='[Generated by Claude]'
[[ "$is_kiro" == true ]] && PREFIX='[Generated by Kiro]'

deny() {
    # Kiro CLI blocks on exit 2 and returns stderr to the model; Claude Code reads a JSON decision.
    if [[ "$is_kiro" == true ]]; then
        echo "$1" >&2
        exit 2
    fi
    jq -n --arg reason "$1" \
        '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: $reason}}'
    exit 0
}

if [[ "$tool_name" == *addCommentToJiraIssue ]]; then
    comment_body="$(jq -r '.tool_input.commentBody // ""' <<<"$input")"
    grep -qF "$PREFIX" <<<"$comment_body" ||
        deny "Jira comments must start with \"$PREFIX\". Put the prefix at the start of commentBody."
    exit 0
fi

command="$(jq -r '.tool_input.command // ""' <<<"$input")"

posts_comment=false
if grep -qE 'gh +(pr|issue) +comment\b' <<<"$command"; then
    posts_comment=true
elif grep -qE 'gh +pr +review\b' <<<"$command" && grep -qE '(^| )(-b|--body|-F|--body-file)( |=)' <<<"$command"; then
    posts_comment=true
elif grep -qE 'gh +api\b' <<<"$command" && grep -qE '/(comments|replies|reviews)\b' <<<"$command" &&
    grep -qE '(^| )(-f|-F|--field|--raw-field|--input|-X|--method)( |=)' <<<"$command" &&
    ! grep -qiE '(-X|--method)( |=)GET\b' <<<"$command"; then
    posts_comment=true
fi

if [[ "$posts_comment" == true ]] && ! grep -qF "$PREFIX" <<<"$command"; then
    deny "Comments posted to GitHub must start with \"$PREFIX\". Put the prefix at the start of the body, inline in the command (not via a body file)."
fi
