#!/usr/bin/env bash
# PreToolUse: blocks posting GitHub comments, replies or reviews (gh via Bash) and Jira comments
# (Atlassian MCP) unless the text contains the "[Generated by Claude]" prefix.
set -euo pipefail

PREFIX='[Generated by Claude]'
input="$(cat)"
tool_name="$(jq -r '.tool_name // ""' <<<"$input")"

deny() {
    jq -n --arg reason "$1" \
        '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: $reason}}'
    exit 0
}

if [[ "$tool_name" == *addCommentToJiraIssue ]]; then
    comment_body="$(jq -r '.tool_input.commentBody // ""' <<<"$input")"
    grep -qF "$PREFIX" <<<"$comment_body" ||
        deny "Jira comments must start with \"$PREFIX\". Put the prefix at the start of commentBody."
    exit 0
fi

command="$(jq -r '.tool_input.command // ""' <<<"$input")"

posts_comment=false
if grep -qE 'gh +(pr|issue) +comment\b' <<<"$command"; then
    posts_comment=true
elif grep -qE 'gh +pr +review\b' <<<"$command" && grep -qE '(^| )(-b|--body|-F|--body-file)( |=)' <<<"$command"; then
    posts_comment=true
elif grep -qE 'gh +api\b' <<<"$command" && grep -qE '/(comments|replies|reviews)\b' <<<"$command" &&
    grep -qE '(^| )(-f|-F|--field|--raw-field|--input|-X|--method)( |=)' <<<"$command" &&
    ! grep -qiE '(-X|--method)( |=)GET\b' <<<"$command"; then
    posts_comment=true
fi

if [[ "$posts_comment" == true ]] && ! grep -qF "$PREFIX" <<<"$command"; then
    deny "Comments posted to GitHub must start with \"$PREFIX\". Put the prefix at the start of the body, inline in the command (not via a body file)."
fi
